{{ if .Values.ingress.enabled}}
{{ if .Values.domain.fqdn.main}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
  generation: 1
  name: {{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}main-consumer-ui-web{{end}}
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}consumer-ui-web{{end}}
              servicePort: http
      host: {{.Values.domain.fqdn.main}}
  tls:
    - hosts:
        - {{.Values.domain.fqdn.main}}
      secretName: letsencrypt-www-{{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}main-consumer-ui-web{{end}}
{{- end}}
{{- if and (.Values.domain.fqdn.forward) ( ne .Values.domain.fqdn.forward "")}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: {{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}forward-consumer-ui-web{{end}}
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}consumer-ui-web{{end}}
              servicePort: http
      host: {{.Values.domain.fqdn.forward}}
  tls:
    - hosts:
        - {{.Values.domain.fqdn.forward}}
      secretName: letsencrypt-www-{{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}forward-consumer-ui-web{{end}}
{{- end}}
{{- end}}
