apiVersion: v1
kind: Service
metadata: 
    name: {{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}consumer-ui-web{{end}}
    labels:
        app: {{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}consumer-ui-web{{end}}
spec: 
    selector:
        app: {{if .Values.nameOverride}}{{.Values.nameOverride}}{{else}}consumer-ui-web{{end}}
        tier: frontend
    ports:
    - name: http
      port: {{.Values.port | default "3000"}}
      protocol: TCP